details
shortintern2020-B-frontier/TeamD pull request #32
Opened 2020-09-09 00:47 UTC by mmmmmeif

ページタイトル、アイコン、ホーム画面の左上に画像を追加しました.

2020-09-09 01:51 UTC, seito2 approved these changes

2020-09-09 01:53 UTC, AkariUC approved these changes

2020-09-09 05:06 UTC, seito2 commented
余裕があればで大丈夫なのですが、ホーム画面、全体的に余白が少ないなあって感じました。。

2020-09-09 07:06 UTC, Ueeek commented
Homeに余白を持たせた。
Homeの サムネイルを小さくした。
sidebarを長くした。

2020-09-09 07:52 UTC, seito2 approved these changes

2020-09-09 07:54 UTC, Ueeek approved these changes

2020-09-09 08:47 UTC, jimmycrequer requested changes
PR name and description lack information.

2020-09-10 03:09 UTC, AkariUC approved these changes

2020-09-10 03:19 UTC, mmmmmeif commented
failed to push some refs to 'https://github.com/shortintern2020-B-frontier/TeamD.git'

2020-09-10 03:21 UTC, t-hoso commented
current branchが遅れているのでもしかしたらローカルのdetailsブランチがリモートより遅れているとかかもしれないなと思いました

2020-09-10 03:25 UTC, merged