use endtime api
shortintern2020-B-frontier/TeamD pull request #39
Opened 2020-09-09 05:24 UTC by Ueeek

[add]
* room (overlay)での、endtimeを apiを叩いて取ってくるようにした。
(fetchだとうまく動かなかったので、axiosでやってます。)

2020-09-09 07:36 UTC, mmmmmeif approved these changes

2020-09-09 07:51 UTC, seito2 approved these changes

2020-09-09 08:21 UTC, jimmycrequer requested changes

2020-09-09 08:21 UTC, jimmycrequer commented on web/src/components/overlay.tsx
> +  const [endtime,setEndtime]=useState<number>(0);
Missing empty spaces between `=`

2020-09-09 08:21 UTC, jimmycrequer commented on web/src/components/overlay.tsx
> +  const [endtime,setEndtime]=useState<number>(0);
Please check the whole PR

2020-09-10 00:21 UTC, Ueeek commented on web/src/components/overlay.tsx
> +  const [endtime,setEndtime]=useState<number>(0);
I applied .eslint to format code.

2020-09-10 03:26 UTC, AkariUC approved these changes

2020-09-10 03:30 UTC, merged