視聴者数のレコードを追加するストアドプロシージャと視聴者数テーブルの変更
shortintern2020-B-frontier/TeamD pull request #41
Opened 2020-09-09 07:58 UTC by t-hoso

主キーをellapse_timeとroom_idに設定しました
また、ストアドプロシージャでレコードを繰り返し追加することができるようになりました

```
mysql> select * from audience where room_id = 1;
+---------+---------------+-------+
| room_id | ellapsed_time | count |
+---------+---------------+-------+
|       1 |             0 |     3 |
|       1 |         60000 |     6 |
|       1 |        120000 |     0 |
|       1 |        180000 |     0 |
|       1 |        240000 |     0 |
|       1 |        300000 |     0 |
|       1 |        360000 |     0 |
|       1 |        420000 |     0 |
|       1 |        480000 |     0 |
|       1 |        540000 |     0 |
|       1 |        600000 |     0 |
|       1 |        660000 |     0 |
|       1 |        720000 |     0 |
|       1 |        780000 |     0 |
|       1 |        840000 |     0 |
|       1 |        900000 |     0 |
|       1 |        960000 |     0 |
|       1 |       1020000 |     0 |
|       1 |       1080000 |     0 |
|       1 |       1140000 |     0
```

2020-09-09 08:13 UTC, jimmycrequer requested changes

2020-09-09 08:13 UTC, jimmycrequer commented on database/migration/schema/V7__create_procedure_insert_audience.sql
> +  DECLARE i INT DEFAULT start_time DIV 60000;
`i` is a bad variable name.

2020-09-09 08:13 UTC, jimmycrequer commented on database/migration/schema/V7__create_procedure_insert_audience.sql
> +  DECLARE end_times CURSOR FOR
`end_times` looks like a collection. Please change variable name so it's easier to understand it is a cursor.

2020-09-09 08:13 UTC, jimmycrequer commented on database/migration/schema/V7__create_procedure_insert_audience.sql
> +  DECLARE i INT DEFAULT start_time DIV 60000;
I think you can remove all the `DIV 60000` and the `*60000` in the insert

2020-09-10 00:29 UTC, jimmycrequer approved these changes

2020-09-10 00:42 UTC, Ueeek commented
audienceのテーブルにinsertされてることが確認できました。

2020-09-10 00:42 UTC, Ueeek approved these changes

2020-09-10 00:50 UTC, seito2 approved these changes

2020-09-10 00:53 UTC, mmmmmeif approved these changes

2020-09-10 01:17 UTC, merged